AWSTemplateFormatVersion: '2010-09-09'
Description: 'Mission Mischief Premium Scraper Infrastructure'

Parameters:
  SSLCertificateArn:
    Type: String
    Description: 'ARN of SSL certificate for custom domain'
    Default: 'arn:aws:acm:us-east-1:ACCOUNT_ID:certificate/CERT_ID'

Resources:
  # DynamoDB Table for posts
  MissionMischiefTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mission-mischief-posts
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: post_id
          AttributeType: S
        - AttributeName: handle
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: post_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: handle-timestamp-index
          KeySchema:
            - AttributeName: handle
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # S3 Bucket for raw data archive
  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'mission-mischief-raw-data-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldRawData
            Status: Enabled
            ExpirationInDays: 90
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Using existing secret: mission-mischief/bright-data-api-key

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: mission-mischief-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: MissionMischiefLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: 
                  - !GetAtt MissionMischiefTable.Arn
                  - !Sub '${MissionMischiefTable.Arn}/index/*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource: 
                  - !GetAtt RawDataBucket.Arn
                  - !Sub '${RawDataBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:aws:secretsmanager:us-east-1:${AWS::AccountId}:secret:mission-mischief/bright-data-api-key-*'
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: '*'

  # Lambda Function
  PremiumScraperLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: mission-mischief-premium-scraper
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          # Placeholder - upload premium-lambda.py as lambda_function.py
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Placeholder'}
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref MissionMischiefTable
          S3_BUCKET: !Ref RawDataBucket
          SCRAPER_SECRET: 'mission-mischief/bright-data-api-key'
      MemorySize: 1024
      Timeout: 900  # 15 minutes

  # EventBridge Rule for daily execution
  DailyScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: mission-mischief-daily-scrape
      Description: 'Trigger scraper daily at 3:00 AM PST'
      ScheduleExpression: 'cron(0 11 * * ? *)'  # 3:00 AM PST = 11:00 UTC
      State: ENABLED
      Targets:
        - Arn: !GetAtt PremiumScraperLambda.Arn
          Id: PremiumScraperTarget

  # Permission for EventBridge to invoke Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PremiumScraperLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DailyScheduleRule.Arn

  # CloudWatch Alarms
  VerificationRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: MissionMischief-LowVerificationRate
      AlarmDescription: 'Alert when verification rate drops below 95%'
      MetricName: VerificationRate
      Namespace: MissionMischief
      Statistic: Average
      Period: 86400  # 24 hours
      EvaluationPeriods: 1
      Threshold: 95
      ComparisonOperator: LessThanThreshold
      TreatMissingData: breaching

  ScrapingFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: MissionMischief-ScrapingFailure
      AlarmDescription: 'Alert when scraping fails'
      MetricName: ScrapingFailures
      Namespace: MissionMischief
      Statistic: Sum
      Period: 3600  # 1 hour
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

  # API Gateway for public access (optional)
  MissionMischiefApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: mission-mischief-api
      Description: 'Mission Mischief public API'
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MissionMischiefApi
      ParentId: !GetAtt MissionMischiefApi.RootResourceId
      PathPart: scrape

  ApiMethodPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MissionMischiefApi
      ResourceId: !Ref ApiResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PremiumScraperLambda.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200

  ApiMethodGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MissionMischiefApi
      ResourceId: !Ref ApiResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PremiumScraperLambda.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200

  ApiMethodOptions:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MissionMischiefApi
      ResourceId: !Ref ApiResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Origin'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
            ResponseTemplates:
              application/json: '{}'
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        PassthroughBehavior: WHEN_NO_MATCH
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: 
      - ApiMethodPost
      - ApiMethodGet
      - ApiMethodOptions
    Properties:
      RestApiId: !Ref MissionMischiefApi
      StageName: prod

  ApiLambdaPermissionPost:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PremiumScraperLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MissionMischiefApi}/*/POST/scrape'

  ApiLambdaPermissionGet:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PremiumScraperLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MissionMischiefApi}/*/GET/scrape'

  # Custom Domain for API
  ApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: scraper.missionmischief.online
      CertificateArn: !Ref SSLCertificateArn
      SecurityPolicy: TLS_1_2
      EndpointConfiguration:
        Types:
          - EDGE

  ApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref ApiDomainName
      RestApiId: !Ref MissionMischiefApi
      Stage: prod

Outputs:
  DynamoDBTable:
    Description: 'DynamoDB table name'
    Value: !Ref MissionMischiefTable
    Export:
      Name: MissionMischief-TableName

  S3Bucket:
    Description: 'S3 bucket for raw data'
    Value: !Ref RawDataBucket
    Export:
      Name: MissionMischief-S3Bucket

  LambdaFunction:
    Description: 'Lambda function ARN'
    Value: !GetAtt PremiumScraperLambda.Arn
    Export:
      Name: MissionMischief-LambdaArn

  ApiEndpoint:
    Description: 'API Gateway endpoint'
    Value: 'https://scraper.missionmischief.online/scrape'
    Export:
      Name: MissionMischief-ApiEndpoint

  CustomDomainTarget:
    Description: 'Custom domain target for DNS'
    Value: !GetAtt ApiDomainName.DistributionDomainName
    Export:
      Name: MissionMischief-DomainTarget