# Sunday Scraper Infrastructure Update
# Convert daily scraper to weekly research validation

Resources:
  # Update EventBridge to Sunday schedule
  BountyHunterSundaySchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: mission-mischief-sunday-scrape
      Description: "Bounty Hunter Sundays - Weekly research validation"
      ScheduleExpression: "cron(0 11 ? * SUN *)"  # 3:00 AM PST Sundays
      State: ENABLED
      Targets:
        - Arn: !GetAtt PremiumScraperLambda.Arn
          Id: "SundayResearchScraper"
          Input: '{"research_mode": true, "generate_leads": true}'

  # New table for direct submissions
  DirectSubmissionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mission-mischief-direct-submissions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: submission_id
          AttributeType: S
      KeySchema:
        - AttributeName: submission_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # New table for research findings
  ResearchFindingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mission-mischief-research-findings
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: finding_id
          AttributeType: S
      KeySchema:
        - AttributeName: finding_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # New table for bounty leads
  BountyLeadsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mission-mischief-bounty-leads
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # Research leads API endpoint
  ResearchLeadsApi:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref AdminApi
      ParentId: !GetAtt AdminApi.RootResourceId
      PathPart: research-leads

  ResearchLeadsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref AdminApi
      ResourceId: !Ref ResearchLeadsApi
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AdminLambda.Arn}/invocations"