service: mission-mischief-scraper

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: prod
  
functions:
  scrape:
    handler: lambda/index.handler
    timeout: 30
    memorySize: 256
    events:
      - http:
          path: scrape
          method: get
          cors: true
    environment:
      NODE_ENV: production